version: '3.8'

include:
  - app/quorus-chorus/docker-compose.yml

services:
  external-api:
    build:
      context: ./external-api
      dockerfile: Dockerfile
    container_name: external-api
    expose:
      - 4001
    ports:
      - 4001:4001
    networks:
      - appnet

networks:
  appnet: