version: '3.8'

include:
  - app/quorus-chorus/docker-compose.yml

services:
  external-api:
    build:
      context: ./external-api
      dockerfile: Dockerfile
    expose:
      - 4001
    ports:
      - 4001:4001
