"""add payout model

Revision ID: bab515c976cf
Revises: baf4b40e6277
Create Date: 2025-08-25 07:43:40.428039

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab515c976cf'
down_revision = 'baf4b40e6277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payouts', sa.Column('isrc', sa.String(length=16), nullable=False))
    op.add_column('payouts', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('payouts', sa.Column('period_start', sa.Date(), nullable=True))
    op.add_column('payouts', sa.Column('period_end', sa.Date(), nullable=True))
    op.add_column('payouts', sa.Column('total_plays', sa.Integer(), nullable=False))
    op.add_column('payouts', sa.Column('payout_per_play', sa.Numeric(precision=9, scale=8), nullable=False))
    op.add_column('payouts', sa.Column('calculation_type', sa.String(length=50), nullable=False))
    op.add_column('payouts', sa.Column('created_at', sa.Date(), nullable=False))
    op.create_index(op.f('ix_payouts_isrc'), 'payouts', ['isrc'], unique=False)
    op.create_foreign_key(None, 'payouts', 'songs', ['isrc'], ['isrc'])
    op.create_unique_constraint(None, 'plays', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'plays', type_='unique')
    op.drop_constraint(None, 'payouts', type_='foreignkey')
    op.drop_index(op.f('ix_payouts_isrc'), table_name='payouts')
    op.drop_column('payouts', 'created_at')
    op.drop_column('payouts', 'calculation_type')
    op.drop_column('payouts', 'payout_per_play')
    op.drop_column('payouts', 'total_plays')
    op.drop_column('payouts', 'period_end')
    op.drop_column('payouts', 'period_start')
    op.drop_column('payouts', 'amount')
    op.drop_column('payouts', 'isrc')
    # ### end Alembic commands ###
