"""add plays table

Revision ID: baf4b40e6277
Revises: a574a93f1bf5
Create Date: 2025-08-25 06:35:18.245719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baf4b40e6277'
down_revision = 'a574a93f1bf5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plays',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('isrc', sa.String(length=16), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['isrc'], ['songs.isrc'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_plays_date'), 'plays', ['date'], unique=False)
    op.create_index(op.f('ix_plays_isrc'), 'plays', ['isrc'], unique=False)
    op.create_unique_constraint(None, 'payouts', ['id'])
    op.create_unique_constraint(None, 'songs', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'songs', type_='unique')
    op.drop_constraint(None, 'payouts', type_='unique')
    op.drop_index(op.f('ix_plays_isrc'), table_name='plays')
    op.drop_index(op.f('ix_plays_date'), table_name='plays')
    op.drop_table('plays')
    # ### end Alembic commands ###
