version: '3.8'

services:
  api:
    build: .
    image: fast_api_base

    ports:
      - '4000:4000'
      - '5678:5678'
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: /bin/bash -c "/app/pre-start.sh && uvicorn app.main:app --host 0.0.0.0 --port 4000 --reload"
    stdin_open: true
    tty: true

  db:
    container_name: postgresql_db
    image: postgres:13

    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
